export const PREFS_LOADED = 'PREFS_LOADED';
export const EXPAND_PANEL = 'EXPAND_PANEL';
export const TOGGLE_PANEL = 'TOGGLE_PANEL';

export const SET_MATERIAL_MEDIA = 'SET_MATERIAL_MEDIA';
export const SET_MATERIAL_SAMPLE_COUNT = 'SET_MATERIAL_SAMPLE_COUNT';

export const SET_PANEL_RECT = 'SET_PANEL_RECT';

export const OPEN_SEARCH = 'OPEN_SEARCH';
export const SET_SEARCH_PAGE_SIZE = 'SET_SEARCH_PAGE_SIZE';
export const SET_SEARCH_PARAMS = 'SET_SEARCH_PARAMS';
export const SEARCH_STARTED = 'SEARCH_STARTED';
export const SEARCH_FULFILLED = 'SEARCH_FULFILLED';
export const SEARCH_REJECTED = 'SEARCH_REJECTED';

export const SET_SEARCH_ENTRY_FORM_PARAM = 'SET_SEARCH_ENTRY_FORM_PARAM';

export const SET_FILTER_SEARCH_VALUE = 'SET_FILTER_SEARCH_VALUE';
