export const PREFS_LOADED = 'PREFS_LOADED';
export const EXPAND_PANEL = 'EXPAND_PANEL';
export const TOGGLE_PANEL = 'TOGGLE_PANEL';

export const SET_MEDIA = 'SET_MEDIA';

export const OPEN_SEARCH = 'OPEN_SEARCH';
export const SET_SEARCH_PAGE_SIZE = 'SET_SEARCH_PAGE_SIZE';
export const SET_SEARCH_PARAMS = 'SET_SEARCH_PARAMS';
export const SEARCH_STARTED = 'SEARCH_STARTED';
export const SEARCH_FULFILLED = 'SEARCH_FULFILLED';
export const SEARCH_REJECTED = 'SEARCH_REJECTED';

export const SET_SEARCH_ENTRY_FORM_PARAM = 'SET_SEARCH_ENTRY_FORM_PARAM';

export const SET_FILTER_SEARCH_VALUE = 'SET_FILTER_SEARCH_VALUE';

export const CLEAR_DETAIL = 'CLEAR_DETAIL';
export const SET_DETAIL_PARAMS = 'SET_DETAIL_PARAMS';
export const DETAIL_READ_STARTED = 'DETAIL_READ_STARTED';
export const DETAIL_READ_FULFILLED = 'DETAIL_READ_FULFILLED';
export const DETAIL_READ_REJECTED = 'DETAIL_READ_REJECTED';

export const INST_SEARCH_STARTED = 'INST_SEARCH_STARTED';
export const INST_SEARCH_FULFILLED = 'INST_SEARCH_FULFILLED';
export const INST_SEARCH_REJECTED = 'INST_SEARCH_REJECTED';
