export const PREFS_LOADED = 'PREFS_LOADED';
export const EXPAND_PANEL = 'EXPAND_PANEL';
export const TOGGLE_PANEL = 'TOGGLE_PANEL';

export const SET_MATERIAL_MEDIA = 'SET_MATERIAL_MEDIA';
export const SET_MATERIAL_SAMPLE_COUNT = 'SET_MATERIAL_SAMPLE_COUNT';

export const SET_PANEL_RECT = 'SET_PANEL_RECT';
